[package]
name = "rust_python_demo"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_python_demo"
crate-type = ["cdylib"]  # 生成Python可加载的动态链接库

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }